INSERT INTO TBL_DOCTOR (NOMBRE, AP_PATERNO, AP_MATERNO, ESPECIALIDAD) VALUES ('LUIS', 'PEREZ', 'PEREZ', 'MEDICO GENERAL');
INSERT INTO TBL_DOCTOR (NOMBRE, AP_PATERNO, AP_MATERNO, ESPECIALIDAD) VALUES ('JORGE', 'DOMINGUEZ', 'DOM', 'MEDICO INTERNISTA');
INSERT INTO TBL_DOCTOR (NOMBRE, AP_PATERNO, AP_MATERNO, ESPECIALIDAD) VALUES ('PEDRO', 'SANCHEZ', 'SANCHEZ', 'PEDIATRA');

INSERT INTO TBL_CONSULTORIO (NUM_CONSULTORIO, PISO) VALUES ('C1', 'PISO 1');
INSERT INTO TBL_CONSULTORIO (NUM_CONSULTORIO, PISO) VALUES ('C2', 'PISO 1');
INSERT INTO TBL_CONSULTORIO (NUM_CONSULTORIO, PISO) VALUES ('C3', 'PISO 2');
INSERT INTO TBL_CONSULTORIO (NUM_CONSULTORIO, PISO) VALUES ('C4', 'PISO 2');

